/* Copyright 2021 SWI-Prolog Solutions b.v.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http:  www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

:- module(ros_services,
          [ ros_client/4,           % +ServiceName, +SrvType, -Client, +Options
            ros_call/3,             % +Client, +Request, -Response
            ros_call/4,             % +Client, +Request, -Response, +Options
            ros_service/4,          % +ServiceName, +SrvType, -Service, +Options
            ros_service_spin/2,     % +Service, :Callback
            ros_service_fold/4,     % +Service, :Callback, +StateStart, -StateEnd
            ros_service_property/2  % +Service, ?Property
          ]).
:- use_module(library(ros)).
:- use_module(library(ros/detail/options)).

:- meta_predicate
    ros_service_spin(+, 2),
    ros_service_fold(+, 4, +, -).

/** <module> ROS services interface

@tbd Register clients with the node
*/

		 /*******************************
		 *       CLIENT INTERFACE	*
		 *******************************/

%!  ros_client(+ServiceName, +SrvType, -Client, +Options) is det.
%
%   Register a client for ServiceName   that  satisfies SrvType. Options
%   processed:
%
%     - node(+Node)
%       Node with which to associate this service
%     - qos_profile(+QoSProfile)
%       Quality of Service profile.

ros_client(ServiceName, SrvType, Client, Options) :-
    node_from_options(Node, Options),
    ros:ros_srv_type_support(SrvType, TypeSupport),
    qos_profile_from_options(QoSProfile, Options),
    ros:'$ros_create_client'(Node, TypeSupport, ServiceName, QoSProfile, Client).

%!  ros_call(+Client, +Request, -Response) is semidet.
%!  ros_call(+Client, +Request, -Response, +Options) is semidet.
%
%   Perform an synchronous call on  Client.   Request  and  Response are
%   dicts that must  conform  the   service  type  description.  Options
%   provided:
%
%     - deadline(+Stamp)
%       Do not wait beyond Stamp.  If `timeout` is also provided this
%       option takes preference.
%     - timeout(+Seconds)
%       Do not wait more than Seconds.  This is translated to
%     - service_info(-Info)
%       If provided, Info is unified with the returned service info
%       represented as a Prolog dict.
%
%   @tbd: what do we do with out-of-sequence replies on the same
%   service?

ros_call(Client, Request, Response) :-
    ros_call(Client, Request, Response, []).

ros_call(Client, Request, Response, Options) :-
    deadline(State, Options),
    ros:ros_send_request(Client, Request, SeqReq),
    option(service_info(ServiceInfo), Options, _),
    must_be(var, ServiceInfo),
    repeat,
      (   deadline_timeout(State, TimeOut)
      ->  ros_wait([Client], TimeOut, Ready),
          Ready = [Client],
          ros:ros_take_response(Client, Response0, ServiceInfo),
          SeqRes = ServiceInfo.request_id.sequence_number,
          (   SeqReq == SeqRes
          ->  !, Response = Response0
          ;   debug(ros(client),
                    'Discarding out-of-sequence response (~p \\== ~p)',
                    [SeqRes, SeqReq]),
              fail
          )
      ;   !, fail
      ).

deadline(deadline(Deadline), Options) :-
    (   option(deadline(Deadline0), Options)
    ->  Deadline = Deadline0
    ;   option(timeout(Timeout), Options)
    ->  get_time(Now),
        Deadline is Now+Timeout
    ;   Deadline = infinite
    ).

deadline_timeout(deadline(Deadline), TimeOut) :-
    (   Deadline == infinite
    ->  TimeOut = infinite
    ;   get_time(Now),
        TimeOut is Deadline - Now,
        TimeOut > 0
    ).


		 /*******************************
		 *       SERVICE INTERFACE	*
		 *******************************/

%!  ros_service(+ServiceName, +SrvType, -Service, +Options)
%
%   Register a server for ServiceName   that  satisfies SrvType. Options
%   processed:
%
%     - node(+Node)
%       Node with which to associate this service
%     - qos_profile(+QoSProfile)
%       Quality of Service profile.

ros_service(ServiceName, SrvType, Service, Options) :-
    node_from_options(Node, Options),
    ros:ros_srv_type_support(SrvType, TypeSupport),
    qos_profile_from_options(QoS, Options),
    ros:'$ros_create_service'(Node, TypeSupport, ServiceName, QoS, Service).

%!  ros_service_spin(+Service, :Callback) is det.
%
%   Register Service to be processed by the  spin loop of the associated
%   node. The response is generated by calling
%
%       call(Callback, Query, Response)

ros_service_spin(Service, Callback) :-
    ros_service_property(Service, name(Name)),
    ros_service_property(Service, node(Node)),
    ros:register_waitable(service(Name), Node, Service, Callback).

%!  ros_service_fold(+Service, :Callback, +StateStart, -StateEnd) is det.
%
%   Process service request while collecting state. On each request this
%   calls
%
%       call(Callback, State, Request, NextState, Response)
%
%   @tbd: currently breaks the  loop  on   failure  or  error. Should we
%   ignore such messages?

ros_service_fold(Service, Callback, StateStart, StateEnd) :-
    repeat,
    ros_wait([Service], 10, Ready),
    Ready = [Service],
    !,
    ros:ros_take_request(Service, Request, Info),
    call(Callback, StateStart, Request, StateNext, Response),
    ros:ros_send_response(Service, Response, Info),
    ros_service_fold(Service, Callback, StateNext, StateEnd).


%!  ros_service_property(+Service, ?Property) is nondet.
%
%   True when Property is a property of Service.

ros_service_property(Service, Property) :-
    ros_service_prop(Property, Service).

ros_service_prop(node(Node), Service) :-
    ros:'$ros_service_prop'(Service, node, Node).
ros_service_prop(name(Name), Service) :-
    ros:'$ros_service_prop'(Service, name, Name).


:- multifile ros:ros_ready/3.

ros:ros_ready(service(_ServiceName), Service, CallBack) :-
    ros:ros_take_request(Service, Request, Info),
    call(CallBack, Request, Response),
    ros:ros_send_response(Service, Response, Info).
